local GlobalConfigConfig = {
	["dock_capacity"] = {"dock_capacity","200",
		[[初始船塢存放人形數量上限（船塢）]],
	},
	["dock_add"] = {"dock_add","20",
		[[單次擴展船塢增加上限數量（船塢）]],
	},
	["dock_cost"] = {"dock_cost","1,1,50",
		[[單次擴展船塢消耗鑽石（船塢）]],
	},
	["dock_limit"] = {"dock_limit","500",
		[[船塢擴展數量上限（船塢）]],
	},
	["player_initial_lv"] = {"player_initial_lv","1",
		[[指揮官初始等級（指揮官）]],
	},
	["player_initial_blackdiamond"] = {"player_initial_blackdiamond","0",
		[[指揮官初始黑鑽（指揮官）]],
	},
	["player_initial_diamond"] = {"player_initial_diamond","0",
		[[指揮官初始鑽石（指揮官）]],
	},
	["player_initial_coin"] = {"player_initial_coin","50000",
		[[指揮官初始金幣（指揮官）]],
	},
	["player_initial_oil"] = {"player_initial_oil","240",
		[[指揮官初始石油（指揮官）]],
	},
	["player_initial_item"] = {"player_initial_item","1,680001,1;25,1031,1;1,160001,1;1,143010,100;1,145101,100;6,4001031,1;2,90010,1;25,1020,1",
		[[指揮官初始道具（指揮官）（道具ID，道具數量）]],
	},
	["player_initial_secretary"] = {"player_initial_secretary","50430",
		[[初始秘書艦]],
	},
	["player_initial_doll"] = {"player_initial_doll","40130,50030,50430,30190,0",
		[[初始編隊人形（人形ID1,人形ID2,人形ID3）]],
	},
	["player_initial_other"] = {"player_initial_other","0",
		[[初始人形（人形ID1，人形ID2，人形ID3）]],
	},
	["player_level_limit"] = {"player_level_limit","80",
		[[指揮官等級上限]],
	},
	["player_initial_BusinessCard"] = {"player_initial_BusinessCard","1,690001,1",
		[[指揮官初始名片背景（道具ID，道具數量）]],
	},
	["character_level_limit"] = {"character_level_limit","80",
		[[人形等級上限]],
	},
	["mail_limit"] = {"mail_limit","200",
		[[郵件上限（郵件）]],
	},
	["depot_item"] = {"depot_item","11;12;13;14",
		[[倉庫中道具分頁包含的道具類型（倉庫）]],
	},
	["depot_equip"] = {"depot_equip","21;22;31",
		[[倉庫中裝備分頁包含的道具類型（倉庫）]],
	},
	["depot_blueprint"] = {"depot_blueprint","32",
		[[倉庫中圖紙分頁包含的道具類型（倉庫）]],
	},
	["DrawCard_Value1"] = {"DrawCard_Value1","1,120001,1",
		[[招募加速消耗（道具ID 1，數量）（注意：第一個道具ID，如果有，就直接使用，如果沒有，就提示使用第二道具ID。）]],
	},
	["DrawCard_Value2"] = {"DrawCard_Value2","1,1,50",
		[[招募加速消耗（道具ID 2，數量；道具ID，數量）（注意：第一個道具ID，如果有，就直接使用，如果沒有，就提示使用第二道具ID。）]],
	},
	["DrawCard_PosScale"] = {"DrawCard_PosScale","-320,60;1.38",
		[[立繪座標]],
	},
	["boatstar_limit"] = {"boatstar_limit","6;6;6;6;6",
		[[不同品質人形星級上限（分別對應未知;N;R;SR;SSR）]],
	},
	["boatstar_limit_reform"] = {"boatstar_limit_reform","6",
		[[深海化&改造船隻星級上限]],
	},
	["boatarouse_itemid"] = {"boatarouse_itemid","1,150001,1",
		[[人形深海化使用道具]],
	},
	["BoatExp"] = {"BoatExp","12",
		[[]],
	},
	["BoatExpMax"] = {"BoatExpMax","99999",
		[[]],
	},
	["Friend_Level"] = {"Friend_Level","5",
		[[推薦好友等級差為5]],
	},
	["Friend_Next_Level"] = {"Friend_Next_Level","1",
		[[逐次放寬等級條件，每次可允許等級差+1]],
	},
	["Friend_OffLineTime"] = {"Friend_OffLineTime","60",
		[[推薦好友離線時間為60分鐘以內]],
	},
	["Friend_Next_OffLineTime"] = {"Friend_Next_OffLineTime","5",
		[[逐次放寬離線時間條件，每次允許離線等級時間增加5分鐘]],
	},
	["Friend_Amount"] = {"Friend_Amount","10",
		[[每次推薦好友10人]],
	},
	["Friend_VisitingCard"] = {"Friend_VisitingCard","15,socialcontact_1_text_0015_bg_2;30,socialcontact_1_text_0015_bg_2;40,socialcontact_1_text_0015_bg;50,socialcontact_1_text_0015_bg",
		[[好友預設名片設定：【等級上限，使用資源】]],
	},
	["Coin_Add_cost"] = {"Coin_Add_cost","10",
		[[快速購買BP時的鑽石消耗]],
	},
	["Oil_Add_cost"] = {"Oil_Add_cost","10",
		[[快速購買能源時的鑽石消耗]],
	},
	["Coin_Add_num"] = {"Coin_Add_num","9999",
		[[單日可購買BP次數上限]],
	},
	["Oil_Add_num"] = {"Oil_Add_num","9999",
		[[單日可購買能源次數上限]],
	},
	["Coin_max"] = {"Coin_max","999999999",
		[[BP數值理論上限]],
	},
	["Oil_max"] = {"Oil_max","2000000",
		[[能源數值理論上限]],
	},
	["Coin_max_buffer"] = {"Coin_max_buffer","1999999999",
		[[BP緩衝上限]],
	},
	["comment_maxcount"] = {"comment_maxcount","50",
		[[]],
	},
	["comment_maxpage"] = {"comment_maxpage","20",
		[[]],
	},
	["Oil_max_buffer"] = {"Oil_max_buffer","3000000",
		[[能源緩衝上限]],
	},
	["boat_max_buffer"] = {"boat_max_buffer","10000",
		[[人偶上限緩衝增加值]],
	},
	["equip_max_buffer"] = {"equip_max_buffer","3000",
		[[裝備緩衝上限]],
	},
	["diamond_max"] = {"diamond_max","50000000",
		[[鑽石數值理論上限]],
	},
	["diamond_max_buffer"] = {"diamond_max_buffer","60000000",
		[[鑽石緩衝上限]],
	},
	["expeditiongroup_base"] = {"expeditiongroup_base","2",
		[[每個角色初始遠征隊列數]],
	},
	["expeditiongroup_add"] = {"expeditiongroup_add","2",
		[[帳號額外可購買遠征隊列數]],
	},
	["site_cost"] = {"site_cost","1,1,100;1,1,300",
		[[購買可執行遠征數的消耗，【type,id,value】]],
	},
	["skin_Add_id"] = {"skin_Add_id","3,7",
		[[]],
	},
	["skin_gold"] = {"skin_gold","1,9,20",
		[[]],
	},
	["slg_tips"] = {"slg_tips","80",
		[[出戰艦隊戰鬥力低於推薦戰鬥力的百分之X，給與彈窗提示]],
	},
	["expedition_task"] = {"expedition_task","101,111,121,131,141",
		[[整備任務的抽取規則，「主類ID，主類ID，……]],
	},
	["base_harbour"] = {"base_harbour","7001",
		[[大地圖初始港口，開發用未來可能刪掉]],
	},
	["married_item"] = {"married_item","1,240020,1",
		[[簽訂誓約消耗的道具ID及數量（CB1專屬誓約戒指，道具ICON為臨時ICON）]],
	},
	["friendliness"] = {"friendliness","6",
		[[簽訂誓約需要的好感等級（測試用]],
	},
	["married_attribute"] = {"married_attribute","1,2,30",
		[[屬性ID，屬性單位（1=具體值；2=千分比），屬性值]],
	},
	["secretary_addfriendlypoint"] = {"secretary_addfriendlypoint","10",
		[[秘書艦每小時所增加的友好度]],
	},
	["sensitivesords_max_replace"] = {"sensitivesords_max_replace","9",
		[[]],
	},
	["friendlylevel_limit"] = {"friendlylevel_limit","9999",
		[[友好度等級上限]],
	},
	["item_limitations"] = {"item_limitations","9999",
		[[單次批量可使用物品數量上限]],
	},
	["materiallv_limit"] = {"materiallv_limit","50",
		[[版本強化等級上限]],
	},
	["materiallv_claim"] = {"materiallv_claim","5",
		[[目前可強化上限=人形lv+X]],
	},
	["materialnum_limit"] = {"materialnum_limit","20",
		[[單次可添加強化素材數量上限]],
	},
	["min_income"] = {"min_income","260002,2,2820;260202,2,2820;260001,2,2820;260201,2,2820",
		[[]],
	},
	["materialadd_value"] = {"materialadd_value","20",
		[[強化吃同ID船時的經驗加成參數【百分比加法】]],
	},
	["materialexp_add"] = {"materialexp_add","0,50,100,150,300",
		[[不同稀有度人形提供基礎強化經驗，順序為"空,N,R,SR,SSR"]],
	},
	["tagadd_limit"] = {"tagadd_limit","2",
		[[圖鑑評論允許添加tag需求的友好度等級]],
	},
	["tagnum_limit"] = {"tagnum_limit","50",
		[[同一人形允許添加tag數量上限]],
	},
	["DrawCard_wait"] = {"DrawCard_wait","20",
		[[招募等待隊列數量]],
	},
	["DrawCard_done"] = {"DrawCard_done","10",
		[[招募完成隊列數量]],
	},
	["DrawCard_start"] = {"DrawCard_start","2",
		[[初始招募隊列數量]],
	},
	["DrawCard_develop"] = {"DrawCard_develop","10",
		[[可擴展招募隊列數量]],
	},
	["DrawCard_cost"] = {"DrawCard_cost","1,1,50",
		[[單次擴展招募隊列消耗]],
	},
	["activity_pass_switch"] = {"activity_pass_switch","1",
		[[小黃本活動全域開關（1=開，0=關）]],
	},
	["activity_resouce"] = {"activity_resouce","6005001",
		[[]],
	},
	["banner_time"] = {"banner_time","10",
		[[Banner每個分頁滯留時間（單位秒）]],
	},
	["loginreward_list"] = {"loginreward_list","1,2,3,4,5,6,7",
		[[簽到獎勵序列（對應簽到配置表LoginReward中的ID）]],
	},
	["battle_Armor_a"] = {"battle_Armor_a","0.025",
		[[護甲減免=（係數a * 護甲）  /  （係數b + 係數c * 護甲）]],
	},
	["battle_Armor_b"] = {"battle_Armor_b","2",
		[[護甲減免=（係數a * 護甲）  /  （係數b + 係數c * 護甲）]],
	},
	["battle_Armor_c"] = {"battle_Armor_c","0.035",
		[[護甲減免=（係數a * 護甲）  /  （係數b + 係數c * 護甲）]],
	},
	["battle_lvSuppress_limit"] = {"battle_lvSuppress_limit","50",
		[[等級壓制 = 1 + ((目前等價壓制高於所配的值/limit)^exp) *（upper - lower）+ lower【只在PVE中有等級壓制才生效，怪物攻擊玩家計算此，玩家攻擊怪物預設為1】]],
	},
	["battle_lvSuppress_exp"] = {"battle_lvSuppress_exp","0.44",
		[[等級壓制 = 1 + ((目前等價壓制高於所配的值/limit)^exp) *（upper - lower）+ lower【只在PVE中有等級壓制才生效，怪物攻擊玩家計算此，玩家攻擊怪物預設為1】]],
	},
	["battle_lvSuppress_upper"] = {"battle_lvSuppress_upper","2",
		[[等級壓制 = 1 + ((目前等價壓制高於所配的值/limit)^exp) *（upper - lower）+ lower【只在PVE中有等級壓制才生效，怪物攻擊玩家計算此，玩家攻擊怪物預設為1】]],
	},
	["battle_lvSuppress_lower"] = {"battle_lvSuppress_lower","0",
		[[等級壓制 = 1 + ((目前等價壓制高於所配的值/limit)^exp) *（upper - lower）+ lower【只在PVE中有等級壓制才生效，怪物攻擊玩家計算此，玩家攻擊怪物預設為1】]],
	},
	["battle_AttribuA"] = {"battle_AttribuA","200;150",
		[[屬性加成 = 1 + ∑屬性 / 係數a【係數a未覺醒 ; 係數a覺醒】]],
	},
	["shop_banner"] = {"shop_banner","trading_1_banner_alphaver_002",
		[[商店主介面banner資源，圖片順序與填入檔案名順序相同，存在多個資源時用,隔開。各banner滯留時間使用banner_time參數]],
	},
	["WorldIntercontinentalCfg"] = {"WorldIntercontinentalCfg","10,7,8,6,9,11,12,13,14,15,16,5,27",
		[[目前版本所使用的大洲配置資訊。]],
	},
	["new_lasted"] = {"new_lasted","30",
		[[new標籤顯示的持續時間，包含上架當天（例：上架時間為20180101，持續時間為30時：①於20180130首次進入商店時顯示new；②於20180131首次進入商店時，不顯示new]],
	},
	["tips_delay_time"] = {"tips_delay_time","2",
		[[條狀tips顯示時長（單位為秒）]],
	},
	["voice_txt_exist"] = {"voice_txt_exist","5",
		[[無語音的文字方塊顯示時長，單位為秒（適用於主介面、總覽、圖鑑）[所有語音通用一個時間]],
	},
	["equip_num_max"] = {"equip_num_max","2000",
		[[倉庫內裝備數量上限]],
	},
	["equip_sell_max"] = {"equip_sell_max","500",
		[[倉庫內裝備批量出售單次上限]],
	},
	["equip_level_limit"] = {"equip_level_limit","10;30;60",
		[[3個頁面對應3個等級段]],
	},
	["monster_lv_limit"] = {"monster_lv_limit","50",
		[[SLG劇情副本生成怪物等級上限]],
	},
	["friendlyLevelDivide"] = {"friendlyLevelDivide","0,1,2,3,6",
		[[普通人偶好感度等級劃分，從左至右分別為厭惡 陌生 友好 心動 愛，即>=0時為陌生階段，>=2時為友好階段以此類推]],
	},
	["ghostfriendlyLevelDivide"] = {"ghostfriendlyLevelDivide","0,1,3,6",
		[[深海化人偶好感度等級劃分，從左至右分別為陌生 友好 心動 愛，即>=0時為陌生階段，>=2時為友好階段以此類推]],
	},
	["char_bones_name"] = {"char_bones_name","zhupaokou;fupaokou;yulei;fashekou;root",
		[[戰鬥人形骨骼收集，包含所有所需的骨骼首碼【假戰鬥專用】]],
	},
	["battle_order"] = {"battle_order","0,10,10",
		[[戰鬥指令參數【初始指令數，指令上限數，指令增長速度1s/1格】]],
	},
	["Questionnaire_Rewards"] = {"Questionnaire_Rewards","1,1,100;2,90010,1",
		[[CB1運營活動-調查問卷完成獎勵]],
	},
	["Strengthen_N_cost"] = {"Strengthen_N_cost","1,2,1500",
		[[強化時，每消耗1張N卡需要消耗的BP數量]],
	},
	["Strengthen_R_cost"] = {"Strengthen_R_cost","1,2,3000",
		[[強化時，每消耗1張R卡需要消耗的BP數量]],
	},
	["Strengthen_SR_cost"] = {"Strengthen_SR_cost","1,2,4500",
		[[強化時，每消耗1張SR卡需要消耗的BP數量]],
	},
	["Strengthen_SSR_cost"] = {"Strengthen_SSR_cost","1,2,9000",
		[[強化時，每消耗1張SSR卡需要消耗的BP數量]],
	},
	["battle_check_val1"] = {"battle_check_val1","8",
		[[戰鬥弱驗證-時間合理數參數]],
	},
	["battle_check_val2"] = {"battle_check_val2","5",
		[[戰鬥弱驗證-傷害合理倍數參數]],
	},
	["player_initial_sprite"] = {"player_initial_sprite",'',
		[[第一編隊初始妖精數量（id,num;id,num;id,num）]],
	},
	["crusade_max_position_num"] = {"crusade_max_position_num","8",
		[[整備任務可能出現的位置數量]],
	},
	["player_register_num"] = {"player_register_num","500000000",
		[[CBT1可註冊帳號上限]],
	},
	["player_register_switch"] = {"player_register_switch","1",
		[[註冊開關（0-關閉註冊；1-開啟註冊）]],
	},
	["player_ment_num"] = {"player_ment_num","0",
		[[設備是否只能註冊一個帳號（0-不限制；1-只能1個帳號）]],
	},
	["Equip_num"] = {"Equip_num","2,0;3,1;4,2;5,3",
		[[裝備副屬性數量：品質越高，副屬性數量越多]],
	},
	["Equip_retrieve"] = {"Equip_retrieve","2,80;3,80;4,80;5,80",
		[[裝備強化經驗回收比例：品質，百分比]],
	},
	["DrawCard_gold"] = {"DrawCard_gold","1,1,100",
		[[招募合約資源兌換比例]],
	},
	["diamond_exchange_rate"] = {"diamond_exchange_rate","10",
		[[資源兌換比例，1RMB=鑽石量]],
	},
	["BP_exchange_rate"] = {"BP_exchange_rate","4000",
		[[資源兌換比例，1RMB=BP量]],
	},
	["oil_exchange_rate"] = {"oil_exchange_rate","60",
		[[資源兌換比例，1RMB=能源量]],
	},
	["battle_time"] = {"battle_time","90",
		[[填入90=倒數計時90S]],
	},
	["battle_start_speed"] = {"battle_start_speed","800",
		[[戰鬥開場入場速度]],
	},
	["emoji"] = {"emoji","20",
		[[小方塊基本表情數量，最後會定為20個]],
	},
	["animation"] = {"animation","28",
		[[角色個人化表情包數量，會新增很多]],
	},
	["Strengthen_proportion"] = {"Strengthen_proportion","80",
		[[強化經驗兌換比例]],
	},
	["Mood_Initial"] = {"Mood_Initial","100",
		[[心情值初始值]],
	},
	["Mood_natural_restoration"] = {"Mood_natural_restoration","5",
		[[心情值每小時自然恢復量]],
	},
	["Mood_battle_cost"] = {"Mood_battle_cost","1",
		[[每次出擊扣除心情值]],
	},
	["Mood_dead_cost"] = {"Mood_dead_cost","1",
		[[每次死亡扣除心情值]],
	},
	["Mood_vow"] = {"Mood_vow","200",
		[[誓約後，心情值提升]],
	},
	["seasocardtask_random"] = {"seasocardtask_random","1,1;2,1;3,1",
		[[季卡每日任務隨機參數]],
	},
	["seasoncard_cost"] = {"seasoncard_cost","60",
		[[季卡購買等級價格]],
	},
	["Equip_manufacture_cost"] = {"Equip_manufacture_cost","1,2,4000",
		[[裝備製作時，每次製作裝備所需消耗的BP數量]],
	},
	["seasoncard_refresh"] = {"seasoncard_refresh","3",
		[[季卡任務每日可更新次數]],
	},
	["seasoncard_votereward"] = {"seasoncard_votereward","1,1,5",
		[[季卡投票獎勵內容]],
	},
	["item_max_num"] = {"item_max_num","9999",
		[[道具單次使用上限]],
	},
	["judge_days"] = {"judge_days","3",
		[[彈出評價的天數]],
	},
	["judge_limit"] = {"judge_limit","2",
		[[總彈窗次數上限]],
	},
	["judge_reward"] = {"judge_reward","1,1,50",
		[[評價獎勵]],
	},
	["judge_story"] = {"judge_story","200104",
		[[彈出評價的關卡id]],
	},
	["judge_switch"] = {"judge_switch","1",
		[[打分提示是否開啟，1開0關]],
	},
	["judge_time_01"] = {"judge_time_01","3",
		[[識別評價是否成功間隔時間(秒)]],
	},
	["judge_time_02"] = {"judge_time_02","43200",
		[[兩次彈窗之間至少間隔時間(秒)]],
	},
	["Shop_hot"] = {"Shop_hot","7",
		[[黑市商品數量]],
	},
	["first_draw_pool"] = {"first_draw_pool","2",
		[[全艦種卡池ID單次首抽固定]],
	},
	["first_draw"] = {"first_draw","20020",
		[[全艦種卡池單次首抽為固定艦娘]],
	},
	["first_draw_ten"] = {"first_draw_ten",'',
		[[全艦種卡池單次十連抽為固定艦娘]],
	},
	["battle_time_check"] = {"battle_time_check","1",
		[[後端戰鬥驗證有效極限時長，單位秒]],
	},
	["battle_time_limit"] = {"battle_time_limit","1800",
		[[後端戰鬥驗證封禁持續時長，單位秒]],
	},
	["notic_head"] = {"notic_head","920001",
		[[聊天系統大頭貼照（resource表ID）]],
	},
	["rename_dialog_list"] = {"rename_dialog_list","name_system01:0.5;name_system02:0.7",
		[[命名界面，對話ID：間隔時間；下一句。]],
	},
	["renovate_cd"] = {"renovate_cd","0.5",
		[[]],
	},
	["question_delay_time"] = {"question_delay_time","0.7",
		[[問題間隔時間]],
	},
	["chose_delay_time"] = {"chose_delay_time","0.5",
		[[選擇間隔時間]],
	},
	["guide_draw_groupid"] = {"guide_draw_groupid","2",
		[[全艦種指定卡池位於第一位]],
	},
	["guide_end"] = {"guide_end","315",
		[[]],
	},
	["troop_skin_01"] = {"troop_skin_01","0",
		[[部隊棋子形象1]],
	},
	["troop_skin_02"] = {"troop_skin_02","3000",
		[[部隊棋子形象2]],
	},
	["troop_skin_03"] = {"troop_skin_03","5000",
		[[部隊棋子形象3]],
	},
	["troop_skin_04"] = {"troop_skin_04","10000",
		[[部隊棋子形象4]],
	},
	["troop_1_scale"] = {"troop_1_scale","100",
		[[單棋子縮放比例]],
	},
	["troop_2_scale"] = {"troop_2_scale","90",
		[[兩個棋子縮放比例]],
	},
	["troop_3_scale"] = {"troop_3_scale","85",
		[[三個棋子縮放比例]],
	},
	["troop_4_scale"] = {"troop_4_scale","75",
		[[四個棋子縮放比例]],
	},
	["troop_5_scale"] = {"troop_5_scale","65",
		[[五個棋子縮放比例]],
	},
	["task_version"] = {"task_version","10",
		[[當前任務版本，如任務配置表更新， 此處版本號+1]],
	},
	["digit_transfer_threhold"] = {"digit_transfer_threhold","100000",
		[[數字轉換為帶k格式時閾值]],
	},
	["quality_excellent"] = {"quality_excellent","4;5",
		[[高品質範圍]],
	},
	["battle_materia_id"] = {"battle_materia_id","11",
		[[狗糧本大洲ID，狗糧本解鎖顯示]],
	},
	["comment_time_limit"] = {"comment_time_limit","30",
		[[評論間隔時間30]],
	},
	["comment_word_limit"] = {"comment_word_limit","30",
		[[評論字數限制30]],
	},
	["comment_num"] = {"comment_num","1000",
		[[普通評論數量1000]],
	},
	["comment_num_hot"] = {"comment_num_hot","10",
		[[熱度評論數量10]],
	},
	["comment_num_limit"] = {"comment_num_limit","50",
		[[普通評論達到一定數量時會出現熱評50]],
	},
	["comment_report_num"] = {"comment_report_num","5",
		[[一天之內最多可舉報的評論數量]],
	},
	["comment_report_disappear"] = {"comment_report_disappear","50",
		[[舉報評論達到一定數量，該評論消失50]],
	},
	["troop_max_num"] = {"troop_max_num","5",
		[[編隊序列數量上限]],
	},
	["troop_unlock_num"] = {"troop_unlock_num","5",
		[[編隊序列預設解鎖數量]],
	},
	["equip_lv_num"] = {"equip_lv_num","100",
		[[裝備強化單次選擇上限]],
	},
	["troop_res_cost_num"] = {"troop_res_cost_num","1,1,{0}",
		[[編隊序列消耗資源類型]],
	},
	["boat_level_limit"] = {"boat_level_limit","10",
		[[素材人偶下限等級]],
	},
	["firstcharge_icon"] = {"firstcharge_icon","activity_1_iconitem_",
		[[首儲介面圖標前綴]],
	},
	["novice_name"] = {"novice_name","activity_1_name_",
		[[新手特派名稱]],
	},
	["seacrystal"] = {"seacrystal","250010",
		[[神秘商店-代幣]],
	},
	["ghost_story"] = {"ghost_story","1136",
		[[深海化劇情引導組]],
	},
	["mvp_ratio"] = {"mvp_ratio","1,1,1",
		[[Mvp評選輸出、傷害承受、治療的計算係數（直接乘該數值）]],
	},
	["newplayer_cardpool"] = {"newplayer_cardpool","9,14",
		[[標記新手卡池ID]],
	},
	["vipcard_commodity"] = {"vipcard_commodity","1,107",
		[[月卡商品id]],
	},
	["vipcard_big"] = {"vipcard_big","250011",
		[[大月卡標識]],
	},
	["vipcard_small"] = {"vipcard_small","250012",
		[[小月卡標識]],
	},
	["vipcard_recharge"] = {"vipcard_recharge","1007,2007",
		[[月卡儲值標識]],
	},
	["story_reward_mail_expiry_data"] = {"story_reward_mail_expiry_data","604800",
		[[劇情港口商店的郵件有效期]],
	},
	["guide_fight_lv"] = {"guide_fight_lv","8",
		[[出征按鈕引導等級]],
	},
	["guide_fight_time"] = {"guide_fight_time","5",
		[[出征按鈕引導等待時間]],
	},
	["GlobalConfig_Mood_SLG_limit_tips"] = {"GlobalConfig_Mood_SLG_limit_tips","40",
		[[心情值低於多少時，出戰會提示]],
	},
	["Site_change_cd"] = {"Site_change_cd","1",
		[[單位：S；每個單位發生變化後生效]],
	},
	["achieve_badge_show"] = {"achieve_badge_show","680001,680002,680003,680004,680005",
		[[成就介面展示徽章匯總]],
	},
	["activity_integral"] = {"activity_integral","10",
		[[]],
	},
	["alliance_task_num"] = {"alliance_task_num","6",
		[[聯盟任務隨機數量]],
	},
	["fish_season_activity_id"] = {"fish_season_activity_id","21,22",
		[[大漁祭活動Id]],
	},
	["story_shop_title"] = {"story_shop_title","exchange_1_head_tittle",
		[[劇情副本商店左上角標題圖]],
	},
	["bigfish_shop_title"] = {"bigfish_shop_title","map_1_head_tittle_fs",
		[[大漁祭商店左上角標題圖]],
	},
	["pvp_victory"] = {"pvp_victory","1,15,10;1,14,10",
		[[勝利獲得積分，代幣]],
	},
	["pvp_fail"] = {"pvp_fail","1,15,0;1,14,5",
		[[失敗獲得積分，代幣]],
	},
	["pvp_seasonday"] = {"pvp_seasonday","30",
		[[演習賽季週期]],
	},
	["pvp_seasonday_interval"] = {"pvp_seasonday_interval","1",
		[[演習賽季週期間隔]],
	},
	["pvp_openlevel"] = {"pvp_openlevel","10",
		[[PVP開放等級]],
	},
	["pvp_refreshtimes"] = {"pvp_refreshtimes","5",
		[[PVP恢復次數上限]],
	},
	["pvp_payforrefreshtimes"] = {"pvp_payforrefreshtimes","5,10,15,20,25,30,35,40,45,50",
		[[PVP付費更新挑戰次數鑽石價格梯度]],
	},
	["pvp_refreshtimesrecover"] = {"pvp_refreshtimesrecover","5400",
		[[PVP每個挑戰次數的恢復時間(秒)]],
	},
	["pvp_dailyrefresh"] = {"pvp_dailyrefresh","12:00:00,18:00:00",
		[[PVP每日定時更新]],
	},
	["pvp_refresh"] = {"pvp_refresh","5",
		[[PVP每日免費更新對手次數]],
	},
	["questionnaire_url_reward"] = {"questionnaire_url_reward","1,1,100;2,90010,1",
		[[問卷獎勵]],
	},
	["questionnaire_url_limit"] = {"questionnaire_url_limit","10101,10",
		[[問卷開放條件]],
	},
	["questionnaire_url_doll"] = {"questionnaire_url_doll","50320",
		[[問卷展示人偶id]],
	},
	["task_type_8_harbour_id"] = {"task_type_8_harbour_id","1",
		[[任務類型8戰鬥次數計算的港口類型id]],
	},
	["material_open_time_offset"] = {"material_open_time_offset","14400",
		[[材料副本開放時間偏移量]],
	},
	["fetters_item_id"] = {"fetters_item_id","240006",
		[[羈絆道具id]],
	},
	["formation_max_number"] = {"formation_max_number","5",
		[[編隊艦娘最大數量]],
	},
	["source_dock"] = {"source_dock","0",
		[[船塢排序是否重置，0為重置，1為不重置，用於跳轉邏輯]],
	},
	["retire_max"] = {"retire_max","100",
		[[回收數量上限]],
	},
	["equip_attribute"] = {"equip_attribute","1,2,5,4,28,3,8,9,35,36",
		[[顯示裝備介面屬性]],
	},
	["equip_type"] = {"equip_type","1;2;3;4;5;6;7;8;9;10",
		[[裝備類型標籤]],
	},
	["equip_type_weight"] = {"equip_type_weight","1,1;2,1;3,1;4,1;5,1;6,1;7,1;8,1;9,1;10,1",
		[[裝備類型隨機權重]],
	},
	["Furniture_region"] = {"Furniture_region","2000000",
		[[佈置用家具，功能家具以ID區分，大於此數為功能家具（該ID無法使用）]],
	},
	["Initial_Reception_Room"] = {"Initial_Reception_Room","1001",
		[[玩家初始會客室房間id]],
	},
	["Visit_Stay_Time"] = {"Visit_Stay_Time","8",
		[[他人參觀停留時間上限]],
	},
	["Visit_Stat_Number"] = {"Visit_Stat_Number","10",
		[[他人參觀停留人數上限]],
	},
	["Lose_House_Mood"] = {"Lose_House_Mood","20",
		[[若人偶被剝奪房間擁有權，將扣除好感度]],
	},
	["debuff_attack_mood"] = {"debuff_attack_mood","1",
		[[流離失所debuff，人偶每次出擊將加扣心情值]],
	},
	["debuff_dead_mood"] = {"debuff_dead_mood","5",
		[[流離失所debuff，人偶每次於出擊中死亡將加扣心情值]],
	},
	["debuff_mood_time"] = {"debuff_mood_time","86400",
		[[流離失所debuff持續時間]],
	},
	["debuff_refresh_time"] = {"debuff_refresh_time","300",
		[[心情值扣減緩衝時間]],
	},
	["backhouse_collect_max"] = {"backhouse_collect_max","200",
		[[後宅收藏數量上限]],
	},
	["backhouse_share_max"] = {"backhouse_share_max","5",
		[[後宅分享數量上限]],
	},
	["backhouse_room_scale"] = {"backhouse_room_scale","3",
		[[後宅主介面房間縮放比例]],
	},
	["backhouse_camera_area"] = {"backhouse_camera_area","-105,135",
		[[後宅主介面鏡頭上下移動區域邊界]],
	},
	["backhouse_bg_scale"] = {"backhouse_bg_scale","4",
		[[後宅背景圖片縮放尺寸]],
	},
	["backhouse_bg_delta"] = {"backhouse_bg_delta","9.8",
		[[後宅背景圖片間距]],
	},
	["backhouse_camera_normal_size"] = {"backhouse_camera_normal_size","32",
		[[後宅預設鏡頭尺寸]],
	},
	["backhouse_camera_focus_size"] = {"backhouse_camera_focus_size","12.25",
		[[後宅聚焦鏡頭尺寸]],
	},
	["backhouse_camera_focus_offset"] = {"backhouse_camera_focus_offset","0.99,-3.42",
		[[後宅聚焦房間偏移量]],
	},
	["backhouse_move_size"] = {"backhouse_move_size","64",
		[[後宅主介面單次鏡頭滑動尺寸（鏡頭佔1/2螢幕）]],
	},
	["backhouse_move_time"] = {"backhouse_move_time","300",
		[[後宅主介面單次滑動時間(ms)]],
	},
	["backhouse_default_floor"] = {"backhouse_default_floor","baseroom_0000001",
		[[後宅房間基本地面]],
	},
	["backhouse_default_wall"] = {"backhouse_default_wall","baseroom_0000002",
		[[後宅房間基本牆面]],
	},
	["formation_default"] = {"formation_default","1",
		[[預設陣型]],
	},
	["battle_cgcutin_delay"] = {"battle_cgcutin_delay","0.2",
		[[大招不進入第二戰場時，動畫播放結束延遲放開時停參數]],
	},
	["battle_uicutin_delay"] = {"battle_uicutin_delay","0.2",
		[[大招不進入第二戰場時，UI插屏播放結束延遲放開時停參數]],
	},
	["battle_declare_time"] = {"battle_declare_time","1.5",
		[[戰鬥宣言人偶喊話文本顯示總時長]],
	},
	["battle_delicious_id"] = {"battle_delicious_id","19",
		[[味蕾革命大洲id，對應活動表跳轉]],
	},
	["totalrecharge_kanbanniang"] = {"totalrecharge_kanbanniang","3016000",
		[[累積儲值活動看板娘資源]],
	},
	["scene_switch"] = {"scene_switch","1",
		[[1=開啟；0=關閉]],
	},
	["food_open_time"] = {"food_open_time","1901,1;1902,2;1903,3;1904,4;1905,5;1906,6;1907,7",
		[[特派僱傭港口解鎖天數，港口id,第幾天解鎖;港口id,第幾天解鎖]],
	},
	["food_activity"] = {"food_activity","30",
		[[特派僱傭港口解鎖天數，港口id,第幾天解鎖;港口id,第幾天解鎖]],
	},
	["pvp_time"] = {"pvp_time","120",
		[[演習戰鬥時長]],
	},
	["pvp_battle"] = {"pvp_battle","9000",
		[[演習戰鬥ID]],
	},
	["prospect_refresh"] = {"prospect_refresh","5",
		[[海上勘查更新次數]],
	},
	["prospect_item"] = {"prospect_item","1,990001,1;1,990002,1;1,990003,1;1,990004,1;1,990005,1;1,990006,1;1,990007,1;1,990008,1",
		[[海上勘查初始贈送道具]],
	},
	["prospect_treasure1"] = {"prospect_treasure1","12",
		[[海上勘查寶藏1數量]],
	},
	["prospect_treasure2"] = {"prospect_treasure2","5",
		[[海上勘查寶藏2數量]],
	},
	["prospect_treasure2_pro"] = {"prospect_treasure2_pro","50",
		[[海上勘查寶藏2每次更新出現的機率（百分比）]],
	},
	["prospect_reward"] = {"prospect_reward","1,18,8;1,18,10",
		[[海上勘查每種寶藏單位兌換代幣基本獎勵（寶藏1；寶藏2）]],
	},
	["prospect_story"] = {"prospect_story","9011",
		[[海上勘查劇情組ID]],
	},
	["chat_reset"] = {"chat_reset","86400",
		[[聊天行為分數重置時間（秒）]],
	},
	["chat_repeat"] = {"chat_repeat","80",
		[[聊天重複標準（百分比）]],
	},
	["chat_initial"] = {"chat_initial","1000",
		[[聊天初始行為分數]],
	},
	["chat_report"] = {"chat_report","20",
		[[聊天檢舉次數每日上限]],
	},
	["chat_report_one"] = {"chat_report_one","1",
		[[單一聊天對象每日檢舉限制]],
	},
	["chat_delay_time"] = {"chat_delay_time","3",
		[[聊天間隔（秒）]],
	},
	["missionsevent_mail"] = {"missionsevent_mail","8",
		[[偶像活動郵件補寄]],
	},
	["season_boat_rate"] = {"season_boat_rate","6025000",
		[[看板娘資源ID]],
	},
	["season_boat_task"] = {"season_boat_task","6025000",
		[[看板娘資源ID]],
	},
	["season_boat_box"] = {"season_boat_box","6025000",
		[[看板娘資源ID]],
	},
	["season_box"] = {"season_box","241021;24102",
		[[遺跡箱基本掉落;額外掉落（dropid）]],
	},
	["map_bg_size"] = {"map_bg_size","1680,960",
		[[世界地圖背景預設大小]],
	},
	["guide_story_textrate"] = {"guide_story_textrate","0.05",
		[[引導劇情對白文本預設的播放速度]],
	},
	["guide_story_textspeed"] = {"guide_story_textspeed","0",
		[[引導劇情對白速度加倍，填0直接出現。]],
	},
	["guide_black"] = {"guide_black","40",
		[[引導功能中的壓黑值]],
	},
	["backhouse_visit_max_num"] = {"backhouse_visit_max_num","4",
		[[後宅自身邀請人偶拜訪數量上限]],
	},
	["BackKeyCD"] = {"BackKeyCD","0.5",
		[[]],
	},
	["pvp_token_id"] = {"pvp_token_id","9000",
		[[演習獲得的代幣ID，ID讀item表]],
	},
	["fps_check"] = {"fps_check","15",
		[[戰鬥平均幀率檢測，上報閾值]],
	},
	["FPS_default_battle"] = {"FPS_default_battle","30",
		[[]],
	},
	["FPS_default_normal"] = {"FPS_default_normal","30",
		[[]],
	},
	["expedition_first"] = {"expedition_first","101101",
		[[整備第一個任務固定]],
	},
	["guide_time"] = {"guide_time","10",
		[[新手引導防卡死點按次數]],
	},
	["guideconfig"] = {"guideconfig","10201,5007",
		[[該新手引導結束後，港口開採資源開始計算groupID]],
	},
	["guide_step"] = {"guide_step","100000;100001",
		[[正常新手引導結束後步驟；非正常新手引導跳過後步驟]],
	},
	["battle_formation_long_press_trigger"] = {"battle_formation_long_press_trigger","0.2",
		[[戰鬥即時拖動人偶更動陣型，拖曳觸發時間]],
	},
	["battle_formation_press_limit"] = {"battle_formation_press_limit","30",
		[[戰鬥即時拖動人偶更動陣型，最大拖曳時間]],
	},
	["suspend_server_time"] = {"suspend_server_time","20",
		[[停服公告請求伺服器的間隔時間，單位s]],
	},
	["exploration_end_delete"] = {"exploration_end_delete","17;18;990001;990002;990003;990004;990005;990006;990007;990008",
		[[海上勘查活動關閉時需刪除的道具]],
	},
	["story_before_name"] = {"story_before_name","1001;1002",
		[[取名前的劇情組]],
	},
	["story_before_battle"] = {"story_before_battle","2002",
		[[取名後開場戰鬥前的劇情組]],
	},
	["story_after_battle"] = {"story_after_battle","2003",
		[[開場戰鬥後的劇情組]],
	},
	["story_after_dress"] = {"story_after_dress","2004",
		[[選擇性別後的劇情組]],
	},
	["data_time"] = {"data_time","300",
		[[資料埋點的上傳間隔時間，單位s]],
	},
	["battle_halfway_skip_init_cooldown"] = {"battle_halfway_skip_init_cooldown","2",
		[[戰鬥途中跳過並直接結算--初始冷卻]],
	},
	["Intrusion_time_max"] = {"Intrusion_time_max","12",
		[[派遣掛機產出最大累計時間（小時）]],
	},
	["Intrusion_time_min"] = {"Intrusion_time_min","1",
		[[派遣掛機產出最小觸發時間（分鐘）]],
	},
	["notice_speed"] = {"notice_speed","8",
		[[跑馬燈速度（秒）]],
	},
	["occupy_battle_time"] = {"occupy_battle_time","10",
		[[反攻鎖定戰鬥時間（秒）]],
	},
	["occupy_boat_cd"] = {"occupy_boat_cd","1",
		[[反攻人偶戰鬥CD（分鐘）]],
	},
	["occupy_bounty_max"] = {"occupy_bounty_max","21",
		[[懸賞未領取獎勵，則不更新上限個數]],
	},
	["occupy_bounty_people"] = {"occupy_bounty_people","5",
		[[懸賞上陣人數]],
	},
	["occupy_bounty_refresh"] = {"occupy_bounty_refresh","4:00:00;12:00:00;18:00:00",
		[[懸賞系統更新時間]],
	},
	["occupy_bounty_surpris"] = {"occupy_bounty_surpris","0.1",
		[[驚喜懸賞出現機率]],
	},
	["occupy_coefficient"] = {"occupy_coefficient","0.5",
		[[反攻係數]],
	},
	["occupy_frozen_after_prop"] = {"occupy_frozen_after_prop","1",
		[[港後被敵軍反攻佔領後，產出的道具是否被凍結]],
	},
	["occupy_frozen_after_prop_deduction"] = {"occupy_frozen_after_prop_deduction","0",
		[[港後被敵軍反攻佔領後，扣除敵軍攜帶道具獎勵的百分比]],
	},
	["occupy_frozen_after_prop_deduction_time"] = {"occupy_frozen_after_prop_deduction_time","0",
		[[港後被敵軍反攻佔領後，扣除敵軍攜帶道具獎勵的最小扣除時間（分鐘）]],
	},
	["occupy_frozen_after_resources"] = {"occupy_frozen_after_resources","100",
		[[港後被敵軍反攻佔領後，產出的資源凍結百分比]],
	},
	["occupy_frozen_after_resources_deduction"] = {"occupy_frozen_after_resources_deduction","0",
		[[港後被敵軍反攻佔領後，扣除凍結資源的百分比]],
	},
	["occupy_frozen_after_resources_deduction_time"] = {"occupy_frozen_after_resources_deduction_time","1",
		[[港後被敵軍反攻佔領後，扣除凍結資源的最小扣除時間（分鐘）]],
	},
	["occupy_frozen_before_prop"] = {"occupy_frozen_before_prop","0",
		[[港口被敵軍反攻佔領前，產出的道具是否被凍結]],
	},
	["occupy_frozen_before_resources"] = {"occupy_frozen_before_resources","100",
		[[港口被敵軍反攻佔領前，產出的資源被凍結的百分比]],
	},
	["occupy_frozen_reward"] = {"occupy_frozen_reward","43.9,-21.7",
		[[反攻獎勵領取位置]],
	},
	["occupy_initial"] = {"occupy_initial","10101,5",
		[[時間反攻初始觸發時機]],
	},
	["occupy_settlement_time"] = {"occupy_settlement_time","30",
		[[反攻結算時間（秒）]],
	},
	["region_color_0"] = {"region_color_0","0,255,255,68",
		[[縮圖我方勢力顏色（黑潮）]],
	},
	["region_color_1"] = {"region_color_1","166,64,93,75",
		[[縮圖敵方勢力顏色（黑峰）]],
	},
	["region_color_100"] = {"region_color_100","255,243,250,86",
		[[反攻佔領的顏色]],
	},
	["region_color_2"] = {"region_color_2","210,146,255,78",
		[[縮圖敵方勢力顏色（薔薇）]],
	},
	["region_color_3"] = {"region_color_3","255,243,250,86",
		[[縮圖敵方勢力顏色（神代）]],
	},
	["region_color_4"] = {"region_color_4","0,198,255,83",
		[[縮圖敵方勢力顏色（銀翼）]],
	},
	["region_color_5"] = {"region_color_5","0,255,255,0",
		[[縮圖敵方勢力顏色（中立）--透明]],
	},
	["notice_max"] = {"notice_max","100",
		[[戰報紀錄上限（條）]],
	},
	["battle_performance_high"] = {"battle_performance_high","10",
		[[戰鬥畫質等級-高畫質]],
	},
	["battle_performance_middle"] = {"battle_performance_middle","20",
		[[戰鬥畫質等級-中畫質]],
	},
	["open_sequence"] = {"open_sequence","1,1101;1,1102;2;1,1108;1,1109;3;1,1123;4;1,1110;1,1112",
		[[開場順序]],
	},
	["fetters_robot_level"] = {"fetters_robot_level","1",
		[[演習機器人羈絆等級]],
	},
	["boat_exp_current"] = {"boat_exp_current","24",
		[[升級經驗值資源ID]],
	},
	["open_sdk"] = {"open_sdk","1000",
		[[sdk開始之前的劇情組]],
	},
	["occupy_red_dot"] = {"occupy_red_dot","1",
		[[紅點開始顯示的累計時間（分鐘）]],
	},
	["WORLD_RATIO_FAR"] = {"WORLD_RATIO_FAR","0.2",
		[[世界地圖常規圖-細節圖（100%）]],
	},
	["WORLD_RATIO_NORMAL"] = {"WORLD_RATIO_NORMAL","0.5",
		[[世界地圖常規圖-縮圖（0%）]],
	},
	["WORLD_RATIO_FOCUS_DEFAULT"] = {"WORLD_RATIO_FOCUS_DEFAULT","0.75",
		[[點擊港口聚焦比例]],
	},
	["WORLD_RATIO_DEFAULT"] = {"WORLD_RATIO_DEFAULT","0.2",
		[[初次進入世界地圖比例]],
	},
	["WORLD_CORE"] = {"WORLD_CORE","60,224,156",
		[[中心位置座標]],
	},
	["WORLD_CORE_NEW"] = {"WORLD_CORE_NEW","-283,-3363,-2277",
		[[]],
	},
	["blitzkrieg_skip_num"] = {"blitzkrieg_skip_num","2",
		[[深海閃擊基於目前大洲閃擊進度的順序id減去該值後，[1~結果值]的港口可跳過戰鬥]],
	},
	["notice_time"] = {"notice_time","20",
		[[跑馬燈延遲時間（秒）]],
	},
	["notice_repeat_time"] = {"notice_repeat_time","90",
		[[跑馬燈循環時間（秒）]],
	},
	["delay_time_trigger_capture"] = {"delay_time_trigger_capture","200",
		[[壓制戰力波動延時（秒）]],
	},
	["delay_time_trigger_stationed"] = {"delay_time_trigger_stationed","500",
		[[駐紮戰力波動延時（秒）]],
	},
	["player_sortie_type"] = {"player_sortie_type","5,6",
		[[個人資訊介面出擊數統計的港口類型]],
	},
	["program_LoginServerPage_serverPageCount"] = {"program_LoginServerPage_serverPageCount","5",
		[[]],
	},
	["program_OccupyRewardForm_AvatarID"] = {"program_OccupyRewardForm_AvatarID","5043000",
		[[]],
	},
	["program_Ranking_Show_Num"] = {"program_Ranking_Show_Num","100",
		[[]],
	},
	["program_Ranking_Special_Num"] = {"program_Ranking_Special_Num","3",
		[[]],
	},
	["Oil_Add_id"] = {"Oil_Add_id","3,2",
		[[快捷購買能源對應商品id]],
	},
	["Coin_Add_id"] = {"Coin_Add_id","3,1",
		[[快捷購買BP對應商品id]],
	},
	["battle_story_id"] = {"battle_story_id","27",
		[[劇情副本大洲id，對應uicfg功能解鎖用]],
	},
	["MapDragMoveSpeed"] = {"MapDragMoveSpeed","1",
		[[滑動靈敏度]],
	},
	["MapTouchScaleSpeed"] = {"MapTouchScaleSpeed","1",
		[[縮放靈敏度]],
	},
	["MapDoubleDragSpeed"] = {"MapDoubleDragSpeed","1",
		[[雙指靈敏度]],
	},
	["delay_time_trigger_times"] = {"delay_time_trigger_times","1",
		[[戰力波動類型每個港口每天觸發X次]],
	},
	["Z_direction"] = {"Z_direction","-15",
		[[Z方向偏移線]],
	},
	["Monoploy_reward"] = {"Monoploy_reward","1,880003,3",
		[[大富翁指定點數道具;雙骰子道具;代幣;骰子]],
	},
	["monopoly_dice_anim_interval"] = {"monopoly_dice_anim_interval","0.8",
		[[]],
	},
	["monopoly_dice_disappear_time"] = {"monopoly_dice_disappear_time","0.5",
		[[]],
	},
	["monopoly_dice_select_delay"] = {"monopoly_dice_select_delay","0.3",
		[[]],
	},
	["monopoly_item_dice"] = {"monopoly_item_dice","880003",
		[[]],
	},
	["monopoly_story_floor_1"] = {"monopoly_story_floor_1","8102,8103",
		[[欲念之骰活動劇情（未生效]],
	},
	["monopoly_story_floor_2"] = {"monopoly_story_floor_2","8104,8105,8106",
		[[欲念之骰活動劇情（未生效]],
	},
	["monopoly_story_floor_3"] = {"monopoly_story_floor_3","8107,8108,8109,8110",
		[[欲念之骰活動劇情（未生效]],
	},
	["monopoly_story_start"] = {"monopoly_story_start","8101",
		[[欲念之骰活動劇情 首次進入]],
	},
	["Bag_red_type_01"] = {"Bag_red_type_01","24",
		[[倉庫出現紅點，使用後消失對應的倉庫道具類型]],
	},
	["battle_anmate"] = {"battle_anmate","0",
		[[戰鬥中手繪動畫是否加速]],
	},
	["Bag_red_type_02"] = {"Bag_red_type_02","30",
		[[倉庫出現紅點，打開介面消失對應的倉庫道具類型]],
	},
	["ndaylogin_bg"] = {"ndaylogin_bg","activity_1_menu_bg_xhzy_20200723",
		[[N日登入背景資源]],
	},
	["ndaylogin_overview"] = {"ndaylogin_overview","activity_1_pic_xhzy_20200723",
		[[N日登入立繪資源]],
	},
	["ndaylogin_overview_axis"] = {"ndaylogin_overview_axis","-240,-95",
		[[N日登入立繪資源座標]],
	},
	["ndaylogin_title"] = {"ndaylogin_title","activity_1_title_xhzy_20200723",
		[[N日登入名稱資源]],
	},
	["ndaylogin_title_axis"] = {"ndaylogin_title_axis","318228",
		[[N日登入名稱資源座標]],
	},
	["ndaylogin_text_color"] = {"ndaylogin_text_color","71ADFF",
		[[N日登入日期文本顏色]],
	},
	["item_division_max"] = {"item_division_max","9999",
		[[材料堆疊數量上限]],
	},
	["loading_text_time"] = {"loading_text_time","500",
		[[判斷過多少ms出現loading字樣]],
	},
	["Line_max"] = {"Line_max","220",
		[[線出現英文字母的最小長度]],
	},
	["Push_queue"] = {"Push_queue","530,6,25,5440,5430",
		[[世界地圖事件隊列（從左往右）]],
	},
	["pushgift_price_item"] = {"pushgift_price_item","6",
		[[]],
	},
	["pushgift_shop_remove"] = {"pushgift_shop_remove","1;2;3;4;5;6;11;12;13;14;21",
		[[]],
	},
	["materia_num_initial"] = {"materia_num_initial","12",
		[[材料副本初始挑戰次數]],
	},
	["materia_num_reply"] = {"materia_num_reply","14400",
		[[材料副本自動回復時間(s)]],
	},
	["materia_num_max"] = {"materia_num_max","6",
		[[材料副本最大上限次數]],
	},
	["blitzkrieg_num_initial"] = {"blitzkrieg_num_initial","10",
		[[閃擊初始挑戰次數（暫時不用了，改為無限制次數，保留配置以便再次使用）]],
	},
	["blitzkrieg_num_reply"] = {"blitzkrieg_num_reply","300",
		[[閃擊自動回復時間(s)（暫時不用了，改為無限制次數，保留配置以便再次使用）]],
	},
	["blitzkrieg_num_max"] = {"blitzkrieg_num_max","5",
		[[閃擊最大上限次數（暫時不用了，改為無限制次數，保留配置以便再次使用）]],
	},
	["harbour_collect_max"] = {"harbour_collect_max","5",
		[[港口收藏上限次數]],
	},
	["HarbourInfo_output"] = {"HarbourInfo_output","5001",
		[[]],
	},
	["worldmap_menu_open"] = {"worldmap_menu_open","0",
		[[世界地圖快速轉移側邊欄預設是否顯示（0-關閉 1-顯示）]],
	},
	["MapSpeed"] = {"MapSpeed","1.5,4,3.5,1.5",
		[[拖動速度,緩動速度, 雙指滑動,雙點擊]],
	},
	["retire_item_list"] = {"retire_item_list","3;16;27",
		[[回收商店中，獎勵清單顯示的道具ID]],
	},
	["retire_skill_compensate"] = {"retire_skill_compensate","2,100;3,100;4,100;5,100",
		[[品質ID，獎勵衰減（百分比）；]],
	},
	["SalvageAuto_maxTimes"] = {"SalvageAuto_maxTimes","20",
		[[]],
	},
	["SalvageAuto_minTimes"] = {"SalvageAuto_minTimes","1",
		[[]],
	},
	["connecting_text_time"] = {"connecting_text_time","cn,500;tw,600",
		[[判斷過多少ms出現connecting文字]],
	},
	["level_exp"] = {"level_exp","260201",
		[[人偶升級溶液不足時快速使用的道具]],
	},
	["level_bp"] = {"level_bp","260202",
		[[人偶升級BP不足時快速使用的道具]],
	},
	["Region"] = {"Region","-50,50",
		[[色塊位罝]],
	},

}
function GlobalConfigConfig.GetConfig(key)
	local Values = GlobalConfigConfig[key]
	if not Values then
		print_error(key)
		return nil
	end
	local Fields = {["key"] = 1,["value"] = 2,["remarks"] = 3,}
	for k,v in pairs(Fields) do
		Fields[k] = Values[v]
	end
	return Fields 
end
return GlobalConfigConfig