local SoundConfigConfig = {
	["Click"] = {"Click","001_click",
	},
	["Close"] = {"Close","002_close",
	},
	["Switch"] = {"Switch","003_switch",
	},
	["Add"] = {"Add","004_add",
	},
	["Lock"] = {"Lock","005_lock",
	},
	["TipHard"] = {"TipHard","006_tips",
	},
	["Congratulate"] = {"Congratulate","007_congratulate",
	},
	["Notice"] = {"Notice","008_notice",
	},
	["Message"] = {"Message","009_message",
	},
	["Open"] = {"Open","010_open",
	},
	["Gacha"] = {"Gacha","011_gacha",
	},
	["Up"] = {"Up","012_up",
	},
	["Rotate"] = {"Rotate","013_rotate",
	},
	["Equip"] = {"Equip","014_equip",
	},
	["Mapzoom"] = {"Mapzoom","015_mapzoom",
	},
	["Shop"] = {"Shop","015_shop",
	},
	["Fight"] = {"Fight","016_fight",
	},
	["Setoff"] = {"Setoff","016_setoff",
	},
	["Map"] = {"Map","017_map",
	},
	["SlgAreaUnlock"] = {"SlgAreaUnlock","017_slgareaunlock",
	},
	["SlgRadar"] = {"SlgRadar","018_slgradar",
	},
	["SlgBattle"] = {"SlgBattle","019_slgbattle",
	},
	["SlgWarn"] = {"SlgWarn","020_slgwarn",
	},
	["Round"] = {"Round","021_round",
	},
	["Win"] = {"Win","022_win",
	},
	["Lose"] = {"Lose","023_lose",
	},
	["Marry"] = {"Marry","024_marry",
	},
	["SLGAttack"] = {"SLGAttack","025_slgattack",
	},
	["SLGAppear"] = {"SLGAppear","026_slgappear",
	},
	["SLGAreaUnlock"] = {"SLGAreaUnlock","027_slgareaunlock",
	},
	["Breakthrough"] = {"Breakthrough","028_breakthrough",
	},
	["Darken"] = {"Darken","029_darken",
	},
	["BattleWin"] = {"BattleWin","030_battlewin",
	},
	["LvUse"] = {"LvUse","031_lv_use",
	},
	["slgwarntip"] = {"slgwarntip","031_slgwarntip",
	},
	["Tips"] = {"Tips","032_tips",
	},
	["Depth"] = {"Depth","033_depth",
	},
	["Depth1"] = {"Depth1","033_depth_1",
	},
	["LevHabour"] = {"LevHabour","034_levhabour",
	},
	["Load"] = {"Load","035_load",
	},
	["UnLoad"] = {"UnLoad","036_unload",
	},
	["Player1"] = {"Player1","037_player1",
	},
	["Player2"] = {"Player2","038_player2",
	},
	["Boss"] = {"Boss","039_boss",
	},
	["StoryMap"] = {"StoryMap","040_storymap",
	},
	["BattleEnd"] = {"BattleEnd","041_battleend",
	},
	["LevelUp"] = {"LevelUp","042_levelup",
	},
	["SLG1"] = {"SLG1","043_slg1",
	},
	["SLG3"] = {"SLG3","045_slg3",
	},
	["SLG4"] = {"SLG4","046_slg4",
	},
	["SLG5"] = {"SLG5","047_slg5",
	},
	["SLG6"] = {"SLG6","048_slg6",
	},
	["SLG8"] = {"SLG8","050_slg8",
	},
	["SLG9"] = {"SLG9","051_slg9",
	},
	["SLG10"] = {"SLG10","052_slg10",
	},
	["IDCard1"] = {"IDCard1","053_idcard1",
	},
	["IDCard2"] = {"IDCard2","054_idcard2",
	},
	["SSRget"] = {"SSRget","055_ssrget",
	},
	["OccupyTip"] = {"OccupyTip","057_occupy_tip",
	},
	["ACF"] = {"ACF","Darkboom_adx2",
	},
	["LobbyBgm"] = {"LobbyBgm","lobby_main",
	},
	["LoginBgm"] = {"LoginBgm","login_main",
	},
	["SLGBgm"] = {"SLGBgm","slg_main",
	},
	["WorldMapBgm"] = {"WorldMapBgm","worldmap_main",
	},
	["StoryMapBgm"] = {"StoryMapBgm","strorymap_main",
	},
	["UISECuesheet"] = {"UISECuesheet","UISE",
	},
	["StorySECuesheet"] = {"StorySECuesheet","StorySE",
	},
	["BattleSECuesheet"] = {"BattleSECuesheet","BattleSE",
	},
	["Battlevictory"] = {"Battlevictory","victory",
	},
	["Battledefeat"] = {"Battledefeat","defeat",
	},

}
function SoundConfigConfig.GetConfig(key)
	local Values = SoundConfigConfig[key]
	if not Values then
		print_error(key)
		return nil
	end
	local Fields = {["key"] = 1,["value"] = 2,}
	for k,v in pairs(Fields) do
		Fields[k] = Values[v]
	end
	return Fields 
end
return SoundConfigConfig